<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sentry_bringup</name>
  <version>0.1.0</version>
  <description>ROS2 nodes for Smart Agri Sentry RDK X5</description>
  <maintainer email="team@example.com">team</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>sentry_interfaces</depend>
  <depend>cv_bridge</depend>
  <depend>ament_index_python</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>nav2_bringup</depend>
  <depend>robot_localization</depend>
  <depend>robot_state_publisher</depend>
  <depend>tf2_ros</depend>
  <depend>sentry_advisory</depend>
  <depend>sentry_data_logger</depend>
  <depend>sentry_fusion</depend>
  <depend>sentry_lidar</depend>
  <depend>sentry_mission</depend>
  <depend>sentry_sensors</depend>
  <depend>sentry_servo</depend>
  <depend>sentry_vision</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
